version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432  # banco acessível pela máquina local via localhost:5432
    volumes:
      - userdb_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  userdb_data: